### PR TITLE
Fix the success response code interval

### PR DESCRIPTION
**Pull request by SandroMachado**
`isSuccess()` should return true if the code is in the range [200..300), which means the request was successfully received, understood, and accepted.

### CODE REVIEW

**Comment by SandroMachado** [comment]
R = @afollestad

**Comment by afollestad** [comment]
You don't have to mention me, I get notified already. Thank you

**Comment by SandroMachado** [comment]
Sorry :)

**Comment by afollestad** [comment]
It's okay :) you're welcome, your pull request is now live in version 1.3.2

**Pull request merged**
